In [1]:
import pandas as pd
import duckdb
import os

# Questions to Answer:
- DAU/MAU
- Total page views
- Page View by Page
- Referrels
- Devices
- Search terms
- num search to num results
- CTRs
- sponsored vs organic impressions
- total impressions
- business page views
- business sign ups
- Paid businesses

In [12]:
bill_df = pd.read_csv('../user-data.csv')
bill_df.rename(columns={'unique id': 'userId', 'Subscription Plan': 'subscription_plan', 'Subscription Renew Date': 'renew_date'}, inplace=True)
bill_df.head()

  subscription_plan            renew_date                            userId
0               NaN                   NaN  1743547361284x291138005899707260
1            yearly  Apr 10, 2026 3:24 pm  1743547621069x279645472884266780
2            yearly  Apr 10, 2026 9:46 pm  1743549178851x847080663521240200
3               NaN                   NaN  1744134674881x127285411168640110
4               NaN                   NaN  1744157592334x292550965261606100

In [14]:
event_df = pd.DataFrame()

try:
    data_folder = f'event-data'
    data_folder_list = os.listdir(data_folder)
except:
    data_folder = '../event-data'
    data_folder_list = os.listdir('../event-data')

# import data
for file in data_folder_list:
    if file.endswith('.csv'):
        loop_df = pd.read_csv(f'{data_folder}/{file}')
        event_df = pd.concat([event_df, loop_df])

event_df = event_df[event_df['originalTimestamp'] >= '2025-01-01']
df = event_df.merge(bill_df, on='userId', how='left')
print(df.shape)
print(df.columns)
df.head()

(19809, 46)
Index(['originalTimestamp', 'anonymousId', 'userId', 'messageId', 'userAgent',
       'page.path', 'page.referrer', 'page.search', 'page.title', 'page.url',
       'business_id', 'location', 'sponsored_listing', 'category', 'name',
       'path', 'referrer', 'search', 'title', 'url', 'category_properties',
       'name_properties', 'button_name', 'traits', 'userAgentData.brands',
       'userAgentData.mobile', 'userAgentData.platform', 'email',
       'input_value', 'input_num', 'input_name', 'address', 'other_category',
       'city', 'description', 'display_email', 'business_name',
       'main_category', 'parish', 'phone', 'sub_category', 'website',
       'search_text', 'event_type', 'subscription_plan', 'renew_date'],
      dtype='object')

,originalTimestamp,anonymousId,userId,messageId,userAgent,page.path,page.referrer,page.search,page.title,page.url,...,business_name,main_category,parish,phone,sub_category,website,search_text,event_type,subscription_plan,renew_date
0,2025-08-12 01:00:40.081000+00:00,39b9e148-9871-4dae-8fe9-b1f5845d3932,1743547621069x279645472884266780,ajs-next-1754960440081-b5ea6b28-26f4-4f12-9860...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5_0 like...,/search,https://coloradocatholicbusinessdirectory.com/,NaN,Search | Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,impression,yearly,"Apr 10, 2026 3:24 pm"
1,2025-08-12 01:00:34.979000+00:00,39b9e148-9871-4dae-8fe9-b1f5845d3932,1743547621069x279645472884266780,ajs-next-1754960434979-84fe738c-6502-4350-8ddc...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5_0 like...,/,https://coloradocatholics.biz/,NaN,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,page,yearly,"Apr 10, 2026 3:24 pm"
2,2025-08-12 01:01:02.338000+00:00,39b9e148-9871-4dae-8fe9-b1f5845d3932,1743547621069x279645472884266780,ajs-next-1754960462338-55d9b46d-bd7f-490b-b808...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5_0 like...,/business_profile/voda-cleaning-and-restoratio...,https://coloradocatholicbusinessdirectory.com/,NaN,| Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,page,yearly,"Apr 10, 2026 3:24 pm"
3,2025-08-12 01:01:06.103000+00:00,39b9e148-9871-4dae-8fe9-b1f5845d3932,1743547621069x279645472884266780,ajs-next-1754960466103-b46dbd7f-c90b-4808-b00c...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5_0 like...,/business_profile/voda-cleaning-and-restoratio...,https://coloradocatholicbusinessdirectory.com/,NaN,| Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,button_click,yearly,"Apr 10, 2026 3:24 pm"
4,2025-08-12 01:00:35.485000+00:00,39b9e148-9871-4dae-8fe9-b1f5845d3932,1743547621069x279645472884266780,ajs-next-1754960435485-738c6502-a350-4ddc-aac1...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5_0 like...,/,https://coloradocatholics.biz/,NaN,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,impression,yearly,"Apr 10, 2026 3:24 pm"

In [8]:
df[df['event_type'] == 'db_update']

,originalTimestamp,anonymousId,userId,messageId,userAgent,page.path,page.referrer,page.search,page.title,page.url,...,description,display_email,business_name,main_category,parish,phone,sub_category,website,search_text,event_type
42,2025-08-12 03:22:03.418000+00:00,2dec65bf-9713-4f8d-88fd-9ba504688aa2,1754949567759x639105313824555300,ajs-next-1754968923418-30a05222-d04e-4e50-94c7...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Clara Rose Creative (CRC) is a faith-driven de...,hello@clararosecreative.com,Clara Rose Creative,Other,St. Isidores Church,(720)926-1556,NaN,https://www.clararosecreative.com,NaN,db_update
113,2025-08-11 16:04:44.101000+00:00,038a9456-eea8-47f2-97cf-6f50150464db,1754927931120x470668069008822300,ajs-next-1754928284101-9b0ade40-0f41-4483-b9c1...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Tony Capra Plumbing & Heating has served the D...,carlo@tonycapra.com,Tony Capra Plumbing and Heating,Home Services,Our Lady of Mount Carmel - Littleton,3032961966,"Plumbing, Heating & Air Conditioning",www.tonycapra.com,NaN,db_update
220,2025-08-11 18:23:43.692000+00:00,e0d0b4da-32c9-46fb-bb29-3fb4f12a82c8,1753982403438x535213824960417500,ajs-next-1754936623692-1b5633c0-47ab-49f3-a3a7...,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Choosing Fidelis means aligning your financial...,tedm@fideliscu.org,Fidelis Catholic Credit Union,Finance,NaN,303.424.5037,Banking and Financial Services,www.fideliscu.org/about,NaN,db_update
249,2025-08-11 18:29:29.937000+00:00,e0d0b4da-32c9-46fb-bb29-3fb4f12a82c8,1753982403438x535213824960417500,ajs-next-1754936969937-76c7b87a-cac4-4e57-8256...,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Choosing Fidelis means aligning your financial...,tedm@fideliscu.org,Fidelis Catholic Credit Union,Finance,St. Mary - Littleton,303.424.5037,Banking and Financial Services,www.fideliscu.org/about,NaN,db_update
303,2025-08-11 18:22:19.591000+00:00,e0d0b4da-32c9-46fb-bb29-3fb4f12a82c8,1753982403438x535213824960417500,ajs-next-1754936539591-8586e5c0-4cd8-47a9-8be3...,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Choosing Fidelis means aligning your financial...,marketing@fideliscu.org,Fidelis Catholic Credit Union,Finance,NaN,303.424.5037,Banking and Financial Services,www.fideliscu.org/about,NaN,db_update
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2025-08-18 17:33:11.484000+00:00,54542fdc-8d86-40b2-b30b-0b00c569c183,1755533063776x956164571796881400,ajs-next-1755538391484-6c68e54e-e945-491c-a9b6...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,"MetalArc, LLC is a family-owned welding and fa...",sales@metalarcdenver.com,"MetalArc, LLC",Home Services,Our Lady of Lourdes - Denver,7204414654.0,Architectural Metalwork and Welding,www.metalarcdenver.com,NaN,db_update
140,2025-08-19 16:53:40.494000+00:00,cd822ab4-5046-491a-8bc6-b67f8c0c0414,1755621956288x571897163769246900,ajs-next-1755622420494-b79af240-0b2a-4e14-9612...,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,GarLo’s Detailing provides full service car wa...,garlos.detailing@hotmail.com,GarLo’s Mobile Detailing,Home Services,St. Thomas More,7205610172.0,Car detailing,Www.garlosdetailing.com,NaN,db_update
60,2025-08-20 14:51:18.243000+00:00,afa0ba5d-034e-449b-a6a5-0a3b32c067fd,1752717497153x537286585580736960,ajs-next-1755701478243-ad2cc3f1-c4d7-4749-9982...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,"Office Rebel provides hands-on, executive-leve...",officerebelllc@gmail.com,Office Rebel Freelance Secretary,Marketing/B2B,St. Mary of the Assumption - Central City,970-281-7096,Administrative,www.officerebel.co,NaN,db_update
103,2025-08-21 05:24:14.335000+00:00,d2b1de0d-658f-4f23-a974-fc323eab2434,1744579851707x640487742075829500,ajs-next-1755753854335-9952d22e-a0b4-4969-8be3...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Dealing with a leaky roof or thinking about an...,info@rooftechnologies.com,"Roof Technologies, LLC",Home Services,Our Lady of Mount Carmel - Littleton,855 766-3001,Roofing / Solar / Siding,www.RoofTechnologies.com,NaN,db_update
26,2025-08-21 05:24:14.335000+00:00,d2b1de0d-658f-4f23-a974-fc323eab2434,1744579851707x640487742075829500,ajs-next-1755753854335-9952d22e-a0b4-4969-8be3...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/dashboard,https://coloradocatholicbusinessdirectory.com/,?view=list,Colorado Catholic Business Directory,https://coloradocatholicbusinessdirectory.com/...,...,Dealing with a leaky roof or thinking about an...,info@rooftechnologies.com,"Roof Technologies, LLC",Home Services,Our Lady of Mount Carmel - Littleton,855 766-3001,Roofing / Solar / Siding,www.RoofTechnologies.com,NaN,db_update

In [4]:
df['event_type'].value_counts()

event_type
impression       4207
page             2856
button_click     1240
identify          516
input_changed     487
search            381
db_update          84
Name: count, dtype: int64

In [5]:
query = """
with base as (
    SELECT DATE(originalTimestamp) as the_date, COALESCE(userId, anonymousId) as user_id
    FROM df 
)

select the_date, count(distinct user_id) as dau 
from base
group by the_date
order by the_date
"""
dau = duckdb.sql(query).df()
print(dau.shape)
dau.head()

(87, 2)

    the_date  dau
0 2023-06-11    1
1 2025-04-28    2
2 2025-04-29   18
3 2025-04-30    8
4 2025-05-01   12

In [6]:
query = """
with base as (
    SELECT DATE_TRUNC('month', DATE(originalTimestamp)) as month_year, 
           COALESCE(userId, anonymousId) as user_id
    FROM df 
)

select month_year, count(distinct user_id) as monthly_active_users
from base
group by month_year
order by month_year
"""
mau = duckdb.sql(query).df()
print(mau.shape)
mau.head()

(5, 2)

  month_year  monthly_active_users
0 2023-06-01                     1
1 2025-04-01                    26
2 2025-05-01                   415
3 2025-06-01                   183
4 2025-07-01                   167

In [7]:
query = """
SELECT DATE(originalTimestamp) as the_date, count(distinct messageId) as page_views
FROM df 
WHERE event_type = 'page'
GROUP BY DATE(originalTimestamp)
"""
pvs = duckdb.sql(query).df()
print(pvs.shape)
pvs.head()

(87, 2)

    the_date  page_views
0 2025-05-19          75
1 2025-06-01          10
2 2025-06-05          13
3 2025-06-08          12
4 2025-06-14           9

In [8]:
query = """
with base as (
    SELECT DATE(originalTimestamp) as the_date, 
           COALESCE(userId, anonymousId) as user_id,
           COUNT(DISTINCT messageId) as user_page_views
    FROM df 
    WHERE event_type = 'page'
    GROUP BY DATE(originalTimestamp), COALESCE(userId, anonymousId)
)

SELECT the_date, AVG(user_page_views) as avg_page_views_per_user
FROM base
GROUP BY the_date
ORDER BY the_date
"""
page_views_per_user = duckdb.sql(query).df()
print(page_views_per_user.shape)
page_views_per_user.head()

(87, 2)

    the_date  avg_page_views_per_user
0 2023-06-11                 1.000000
1 2025-04-28                 1.000000
2 2025-04-29                 2.222222
3 2025-04-30                 1.125000
4 2025-05-01                 2.666667

In [9]:
query = """
SELECT "page.referrer" as referrer, count(*) as count
FROM df 
WHERE "page.referrer" is not null
AND event_type = 'page'
GROUP BY "page.referrer"
ORDER BY count DESC
"""
referrers = duckdb.sql(query).df()
print(referrers.shape)
referrers.head()

(15, 2)

                                         referrer  count
0  https://coloradocatholicbusinessdirectory.com/   1748
1                  https://coloradocatholics.biz/    236
2                         https://www.google.com/     56
3                       https://www.facebook.com/     14
4                                 https://bit.ly/      8

In [10]:
query = """
SELECT 
    "userAgentData.platform" as platform,
    count(*) as count
FROM df 
WHERE "userAgentData.platform" is not null
AND event_type = 'page'
GROUP BY "userAgentData.platform"
ORDER BY count DESC
"""
platform_mobile = duckdb.sql(query).df()
print(platform_mobile.shape)
platform_mobile.head(10)

(6, 2)

    platform  count
0    Windows    912
1      macOS    348
2    Android    226
3      Linux     31
4  Chrome OS     18
5        iOS      2

In [12]:
query = """
select event_type, count(*) as count
from df
group by event_type
order by count desc
"""
event_type = duckdb.sql(query).df()
print(event_type.shape)
event_type.head(10)

(7, 2)

      event_type  count
0     impression   4207
1           page   2856
2   button_click   1240
3       identify    516
4  input_changed    487
5         search    381
6      db_update     84

In [28]:
query = """
with impressions as (
    SELECT date(originalTimestamp) as the_date, 
    COALESCE(userId, anonymousId) as user_id, 
    sponsored_listing,
    unnest(string_split(business_id, ', ')) as single_business_id
    FROM df
    WHERE event_type = 'impression'
    and sponsored_listing = 'False'
)

, imp_agg as (
select the_date, user_id, count(distinct single_business_id) as business_count
from impressions
group by the_date, user_id
order by the_date, user_id
)

select the_date, avg(business_count) as avg_business_count
from imp_agg
group by the_date
order by the_date
"""
search_results = duckdb.sql(query).df()
print(search_results.shape)
search_results.head(10)

(73, 2)

    the_date  avg_business_count
0 2023-06-11           58.000000
1 2025-04-29           28.000000
2 2025-04-30           28.000000
3 2025-05-01           28.000000
4 2025-05-04           28.000000
5 2025-05-05           28.666667
6 2025-05-06           29.600000
7 2025-05-07           30.714286
8 2025-05-08           32.000000
9 2025-05-09           32.000000

In [34]:
query = """
with impressions as (
    SELECT date(originalTimestamp) as the_date, 
    COALESCE(userId, anonymousId) as user_id, 
    sponsored_listing,
    unnest(string_split(business_id, ', ')) as single_business_id
    FROM df
    WHERE event_type = 'impression'
)

, imp_agg as (
select the_date, single_business_id, sponsored_listing, count(distinct user_id) as num_impressions
from impressions
group by the_date, single_business_id, sponsored_listing
order by the_date, single_business_id, sponsored_listing
)

select the_date, 
avg(case when sponsored_listing = 'False' then num_impressions else null end) as avg_impressions_non_sponsored,
avg(case when sponsored_listing = 'True' then num_impressions else null end) as avg_impressions_sponsored
from imp_agg
group by the_date
order by the_date
"""
impressions = duckdb.sql(query).df()
print(impressions.shape)
impressions.head(10)

(85, 3)

    the_date  avg_impressions_non_sponsored  avg_impressions_sponsored
0 2023-06-11                       1.000000                   1.000000
1 2025-04-28                            NaN                   2.000000
2 2025-04-29                       2.000000                  17.333333
3 2025-04-30                       2.000000                   6.666667
4 2025-05-01                       3.000000                  11.333333
5 2025-05-03                            NaN                   7.000000
6 2025-05-04                       3.000000                   4.333333
7 2025-05-05                       2.965517                  10.000000
8 2025-05-06                       4.933333                  13.666667
9 2025-05-07                       6.718750                  16.333333

In [38]:
query = """
with t1 as (
    SELECT date(originalTimestamp) as the_date, business_id, count(distinct messageId) as page_views
    FROM df 
    WHERE event_type = 'page'
    and business_id is not null
    group by date(originalTimestamp), business_id
)

select the_date, avg(page_views) as avg_page_views
from t1
group by the_date
order by the_date
"""
page_views = duckdb.sql(query).df()
print(page_views.shape)
page_views.head(10)

(73, 2)

    the_date  avg_page_views
0 2025-04-29        1.000000
1 2025-05-01        1.166667
2 2025-05-04        1.384615
3 2025-05-05        2.200000
4 2025-05-06        1.444444
5 2025-05-07        3.000000
6 2025-05-08        1.000000
7 2025-05-09        2.642857
8 2025-05-10        2.812500
9 2025-05-11        1.500000

In [6]:
query = """
with t1 as (
    SELECT date(originalTimestamp) as the_date, business_id, count(distinct messageId) as button_clicks
    FROM df 
    WHERE event_type = 'button_click'
    and button_name = 'visit_website'
    group by date(originalTimestamp), business_id
)

select the_date, avg(button_clicks) as avg_button_clicks
from t1
group by the_date
order by the_date
"""
button_clicks = duckdb.sql(query).df()
print(button_clicks.shape)
button_clicks.head(10)

(52, 2)

    the_date  avg_button_clicks
0 2025-05-01           1.000000
1 2025-05-04           1.000000
2 2025-05-05           1.000000
3 2025-05-06           1.000000
4 2025-05-07           1.000000
5 2025-05-09           1.375000
6 2025-05-10           1.000000
7 2025-05-11           1.500000
8 2025-05-12           1.000000
9 2025-05-13           1.636364

In [ ]:
query = """
select DATE_TRUNC('month', DATE(originalTimestamp)) as month_year, count(distinct userId) as signups
from df
where event_type = 'button_click'
and button_name = 'faith'
group by DATE_TRUNC('month', DATE(originalTimestamp))
order by month_year
"""
signups = duckdb.sql(query).df()
print(signups.shape)
signups.head(10)

(3, 2)

  month_year  signups
0 2025-05-01       20
1 2025-06-01       11
2 2025-07-01        8

In [19]:
query = """
SELECT name, count(*) as count
FROM df 
WHERE event_type = 'page'
GROUP BY name
"""
pvs = duckdb.sql(query).df()
print(pvs.shape)
pvs.head(pvs.shape[0])

(10, 2)

                   name  count
0              about_us    140
1            new-search      7
2  business_profile_new      3
3                 start    174
4              reset_pw     18
5                search   1055
6                 index   1184
7      business_profile    927
8             dashboard    263
9          how_it_works    110

In [18]:
query = """
    SELECT name
    FROM df 
    WHERE event_type = 'page'
    and business_id is not null
    and path like '/business_profile/%'
    """
page_views = duckdb.sql(query).df()
print(page_views.shape)
page_views.head()

(892, 1)

               name
0  business_profile
1  business_profile
2  business_profile
3  business_profile
4  business_profile

In [27]:
query = """
WITH page_sequence AS (
    SELECT 
        DATE_TRUNC('week', DATE(originalTimestamp)) as the_week,
        COALESCE(userId, anonymousId) as user_id,
        name as current_page,
        LEAD(name) OVER (
            PARTITION BY COALESCE(userId, anonymousId) 
            ORDER BY originalTimestamp
        ) as next_page,
        originalTimestamp
    FROM df
    WHERE event_type = 'page'
    AND name IN ('search', 'business_profile')
),
user_weekly_views AS (
    SELECT 
        the_week,
        user_id,
        COUNT(CASE WHEN current_page = 'search' THEN 1 END) as user_search_views,
        COUNT(CASE WHEN current_page = 'business_profile' THEN 1 END) as user_profile_views,
        COUNT(CASE WHEN current_page = 'search' AND next_page = 'business_profile' THEN 1 END)::FLOAT / 
            NULLIF(COUNT(CASE WHEN current_page = 'search' THEN 1 END), 0) as user_ctr
    FROM page_sequence
    GROUP BY the_week, user_id
)
SELECT 
    the_week as the_date,
    AVG(user_search_views) as search_views,
    AVG(user_profile_views) as profile_views,
    AVG(user_ctr) as click_through_rate
FROM user_weekly_views
GROUP BY the_week
ORDER BY the_week
"""
ctr = duckdb.sql(query).df()
print(ctr.shape)
ctr.head()

(17, 4)

    the_date  search_views  profile_views  click_through_rate
0 2025-04-28      1.187500       1.437500            0.272253
1 2025-05-05      2.980769       2.326923            0.401196
2 2025-05-12      2.315789       1.789474            0.384167
3 2025-05-19      4.391304       3.000000            0.358117
4 2025-05-26      1.840000       2.240000            0.496429

## Billing Data

In [5]:
bill_df = pd.read_csv('../user-data.csv')
print(bill_df.shape)
bill_df.head()

(102, 3)

  Subscription Plan Subscription Renew Date                         unique id
0               NaN                     NaN  1743547361284x291138005899707260
1            yearly    Apr 10, 2026 3:24 pm  1743547621069x279645472884266780
2            yearly    Apr 10, 2026 9:46 pm  1743549178851x847080663521240200
3               NaN                     NaN  1744134674881x127285411168640110
4               NaN                     NaN  1744157592334x292550965261606100

In [12]:
query = """
with base as (
    SELECT 
        TRY_CAST(strptime("Subscription Renew Date", '%b %d, %Y %I:%M %p') AS DATE) AS renew_date,
        "Subscription Plan" as subscription_plan,
        count(distinct "unique id") as num_customers
    FROM bill_df
    GROUP BY 1, 2
    ORDER BY 1, 2
)

, rev_calc as (
select *,
case when subscription_plan = 'monthly' then num_customers*20 else num_customers*200 end as revenue
from base
)

select renew_date,
sum(revenue) as estimated_revenue
from rev_calc
group by 1
order by 1
    """
sub_date = duckdb.sql(query).df()
print(sub_date.shape)
sub_date.head()

(9, 2)

  renew_date  estimated_revenue
0 2025-06-09               20.0
1 2025-06-14               20.0
2 2025-06-23               20.0
3 2026-04-10              400.0
4 2026-07-31              200.0